### PR TITLE
Distant Horizons blending

### PR DESCRIPTION
**Pull request by Steveplays28**
Hi, I've been creating compatibility for Distant Horizons and Complementary Reimagined.
Here's the current todo list:

- [x] DH blending (terrain, water, fog, SSAO)
- [x] DH LODs reflecting onto vanilla water
- [x] Toggle in the options screen for DH compat (and usage of the define to go along with it)
- [x] Slider in the options screen for the view distance blend factor (currently hardcoded)
- [x] Fix transparent leaves rendering not showing terrain/water
- [x] Disable border fog when DH compat is enabled
- [x] Fix 2nd transparent leaves issue

Going to PR as draft initially since I'd like to finish these features first, I'm up for discussion on the changes, either here or on Discord, that's no problem.
Example of the blending in action

### CODE REVIEW

**Comment by EminGT** [comment]
This is great. Thank you. I was planning on doing it myself, but this speeds things up a lot as I still have other things I need to work on first

**Comment by Steveplays28** [comment]
I've implemented a config screen and fixed the leaf transparency, everything should be good to go now!
SSR is the only thing left to fix, as discussed in shaderLABS.

**Comment by EminGT** [comment]
Thank you so much! Marking this as a to-do for r5.1 update

**Comment by TheNukeLore** [comment]
as of the latest changes i experience leaf translucent issue still alongside artifacts on the side of the screen

**Comment by Steveplays28** [comment]
I'll try to work on these today.

**Comment by Steveplays28** [comment]
Fixed the leaf issue thanks to [Redotix (Distant Horizons Discord server)](https://discord.com/channels/881614130614767666/1152046626475606077/1154899086621810779).
Next up is border fog, I'll disable it if DH compat is enabled.

**Comment by Steveplays28** [comment]
Hey Emin, it's probably worth waiting until Iris compat is added to DH.
DH recently switched to an Indium dependency instead of a Sodium mixin, so shaders are currently broken.

I'll update this when Iris compat is sorted out.

**Comment by EminGT** [comment]
Oh no, I hope it doesn't take too long for things to get sorted out

**Comment by Steveplays28** [comment]
Hi Emin, there's 1 more thing I'd like to ask IMS before merging this PR, once he's back. with the new Iris update for DH compatibility around the corner.

**Comment by EminGT** [comment]
I think I will leave this for r5.2 and publish r5.1 this week. In the meantime we can direct people to your fork I guess :P

**Comment by Steveplays28** [comment]
The question is/was about the leaf transparency issue that I bandaid patched.
I'm not sure if it's worth exploring fixes/improvements now or in a followup PR, since the fix really shouldn't work afaik.

What do you think, Emin?

**Comment by EminGT** [comment]
I think your current way of doing it seems fine to me. Buffer usage can get complicated really quick. But if it causes issues in the future I can change it myself in an update

**Comment by Steveplays28** [comment]
Alright, then this PR should be ready.

**Comment by imaron85** [comment]
I would like to bump this amazing PR

**Comment by Steveplays28** [comment]
Hi Emin, I'll merge the conflicts when I have time.
Also, I'd like to make another change: increasing the maximum cloud height, all the way up to 1200 or so, maybe more, if that doesn't create issues with Iris.

**Comment by Steveplays28** [comment]
Not sure why there's still conflicts on the PR.
I broke the shaderpack config menu, I'll fix that.

**Comment by EminGT** [comment]
No need to worry about the conflicts as the support is done now for the r5.2 update. Thank you for your help Steve! This PR was a very good starting point, and the upcoming option extends on it with tweaked DH chunk colors and some extra fixes/changes

**Comment by Steveplays28** [comment]
Alright! No problem, was really fun to work on.
Nice! Null suggested moving the blending to the final postprocess step with composites, if that's not already in your planned changes (sounds like it to me).

> There are conflicts in the PR because you (or Emin) didn't properly update it to the latest version. You should've merged the upstream changes, but it looks like they were cherry-picked. I'll see if I can fix this

Apologies, forgot I could just rebase the last 2 commits or manually merge them in and that cherrypicking doesn't work. Hope it's not that big of a hassle.

**Comment by Steveplays28** [comment]
That's awesome, nice Emin!
Really stoked to see the changes when they go live.

**Comment by Kilgorio** [comment]
image
yea I mean this is horrible. I enabled skybox reflections and it fixed it so yee?

**Comment by Kilgorio** [comment]
image
and why

**Comment by Steveplays28** [comment]
Clouds being rendered through LODs is something Emin is working on for the release.

**Comment by Kilgorio** [comment]
okay

**Comment by NatoBoram** [comment]
Seems like Distant Horizons claims the shaderspack doesn't support it

**Comment by imaron85** [comment]
@NatoBoram yes, this is intended behavior as far as I am aware. This shader pack was made as a hacky temporary solution, because DH and iris didnt work together at all. It just blended the chunks, instead of shading the DH chunks, which iris and DH have now figured out. So you can get the real deal.

**Comment by Steveplays28** [comment]
Indeed. As imaron85 said, use release Iris/Oculus for this fork, not the new `v1.7.0` in-dev version.

**Comment by Steveplays28** [comment]
I'm closing this PR, since Emin already has Iris + DH support `v2` up and running on Patreon.

**Pull request closed without merging**
